name: target-branch-is-canary
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
jobs:
  # Disallow all merged that are not from the canary branch
  disallow:
    runs-on: ubuntu-latest
    steps:
      - name: disallow if not from canary
        if: ${{ github.base_ref != 'canary' && github.head_ref != 'changeset-release/from-canary' }}
        run: |
          echo "Please target the canary branch, only releases are supposed to be merged into main (base_ref: ${{ github.base_ref }},  head_ref: ${{ github.head_ref }})"
          exit 1
